<!DOCTYPE html>
<html>
<head>
  <title><?php echo $appName; ?></title>
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="css/style.css"  media="screen,projection"/>

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body>
    <?php echo $this->partial('header'); ?>
    <?php echo $this->partial('sidenav'); ?>
    <div class="container"><?php echo $this->getContent(); ?></div>
    <?php echo $this->partial('footer'); ?>

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="js/materialize.min.js"></script>
    <script>
       $(document).ready(function(){
           $('.button-collapse').sideNav();
           $('.carousel').carousel();
       });
   </script>
</body>
</html>