<ul id="slide-out" class="side-nav">
    <li><div class="userView">
        <div class="background">
            <img src="http://lorempixel.com/350/350/nature/2">
        </div>
        <a href="#!user"><img class="circle" src="http://lorempixel.com/250/250/nature/1"></a>
        <a href="#!name"><span class="white-text name">John Doe</span></a>
        <a href="#!email"><span class="white-text email">jdandturk@gmail.com</span></a>
    </div></li>
    <li><a href="#!"><i class="material-icons">cloud</i>First Link With Icon</a></li>
    <li><a href="#!">Second Link</a></li>
    <li><div class="divider"></div></li>
    <li><a class="subheader">Subheader</a></li>
    <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
</ul>
