<div class="carousel">
    <a class="carousel-item" href="#one!"><img src="http://lorempixel.com/250/250/nature/1"></a>
    <a class="carousel-item" href="#two!"><img src="http://lorempixel.com/250/250/nature/2"></a>
    <a class="carousel-item" href="#three!"><img src="http://lorempixel.com/250/250/nature/3"></a>
    <a class="carousel-item" href="#four!"><img src="http://lorempixel.com/250/250/nature/4"></a>
    <a class="carousel-item" href="#five!"><img src="http://lorempixel.com/250/250/nature/5"></a>
</div>

<div class="row">
    <div class="col s12 m6 l3">
      <div class="card">
        <div class="card-image">
          <img src="http://lorempixel.com/250/250/nature/1">
          <a class="btn-floating activator halfway-fab waves-effect waves-light red"><i class="material-icons">list</i></a>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="card-reveal">
           <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
           <p>Here is some more information about this product that is only revealed once clicked on.</p>
                <div>Location:</div>
                <div class="chip">
                    <img src="http://lorempixel.com/250/250/nature/1" alt="Contact Person">Lippo Mall
                </div>
                <div class="chip">
                    <img src="http://lorempixel.com/250/250/nature/2" alt="Contact Person">Mall Arta Gading
                </div>
                <div class="chip">3 more..</div>
        </div>
      </div>

  </div>
    <div class="col s12 m6 l3">
      <div class="card">
        <div class="card-image">
          <img src="http://lorempixel.com/250/250/nature/2">
          <a class="btn-floating activator halfway-fab waves-effect waves-light red"><i class="material-icons">list</i></a>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">Card Title</span>
          <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="card-reveal">
           <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
           <p>Here is some more information about this product that is only revealed once clicked on.</p>
                <span>Location:</span>
                <div class="chip">
                    <img src="http://lorempixel.com/250/250/nature/1" alt="Contact Person">Lippo Mall
                </div>
                <div class="chip">
                    <img src="http://lorempixel.com/250/250/nature/2" alt="Contact Person">Mall Arta Gading
                </div>
                <div class="chip">3 more..</div>
        </div>
      </div>
    </div>
    <div class="col s12 m6 l3">
      <div class="card">
        <div class="card-image">
          <img src="http://lorempixel.com/250/250/nature/1">
          <span class="card-title">Card Title</span>
          <a class="btn-floating activator halfway-fab waves-effect waves-light red"><i class="material-icons">list</i></a>
        </div>
        <div class="card-content">
          <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="card-reveal">
           <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
           <p>Here is some more information about this product that is only revealed once clicked on.</p>
        </div>
      </div>
    </div>
    <div class="col s12 m6 l3">
      <div class="card">
        <div class="card-image">
          <img src="http://lorempixel.com/250/250/nature/2">
          <span class="card-title">Card Title</span>
          <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">add</i></a>
        </div>
        <div class="card-content">
          <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
        </div>
      </div>
    </div>
</div>

<div class="fixed-action-btn toolbar">
    <a class="btn-floating btn-large red">
      <i class="large material-icons">search</i>
    </a>
    <ul>
      <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">insert_chart</i></a></li>
      <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">format_quote</i></a></li>
      <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">publish</i></a></li>
      <li class="waves-effect waves-light"><a href="#!"><i class="material-icons">attach_file</i></a></li>
    </ul>
  </div>